- name: Setup React project environment
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
      become: yes


    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Add Node.js 20 repository and install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash
      become: yes

    - name: Ensure n is installed (Node.js version manager)
      npm:
        name: n
        global: yes

    - name: Upgrade Node.js to latest LTS version
      command: n lts
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"

    - name: Clone your React project from Git repository
      git:
        repo: 'https://github.com/KDim67/BoostFlow.git'
        dest: "{{ app_dir }}"
        version: main
      become: false

    - name: Create .env file for Firebase config
      copy:
        dest: /home/ubuntu/react-app/.env
        content: |
          NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyBCtUP_65uVdnUjquBzNs3SwrWgtVo6zxg
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=flow-dd81b.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=flow-dd81b
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=flow-dd81b.firebasestorage.app
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=355622781118
          NEXT_PUBLIC_FIREBASE_APP_ID=1:355622781118:web:8b923119d0fd0ce1ae5eef
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-8T9KQV6PNF
      become: false


    - name: Install React project dependencies
      npm:
        path: "{{ app_dir }}"
        state: present
      become: false

    - name: Build React app (optional)
      command: npm run build
      args:
        chdir: "{{ app_dir }}"
      become: false

