---
 - name: install spring boot application
   hosts: all

   tasks:
     - name: show app_dir value
       ansible.builtin.debug:
         msg: "app_dir is {{ app_dir }}"

     - name: install java
       apt:
         name: openjdk-21-jdk
         state: present
         update_cache: yes
       become: yes

     - name: clone git repo
       git:
         repo: 'https://github.com/tsadimasteaching/ds-lab-2024.git'
         dest: "{{ app_dir }}"
         version: api
         force: yes
