---
- name: Install Docker
  hosts: azure_hosts
  become: yes
  tasks:
    - name: Install basic packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
        update_cache_retries: 5
        update_cache_retry_max_delay: 10
      loop:
        - software-properties-common
        - curl
        - apt-transport-https
        - ca-certificates

    - name: Get Docker GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
      register: docker_repo_added

    - name: Clean apt cache after adding Docker repository
      command: apt-get clean
      when: docker_repo_added.changed

    - name: Install Docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
        update_cache_retries: 5
        update_cache_retry_max_delay: 10
      loop:
        - docker-ce
        - docker-compose

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes