---
all:
  children:
    azure_hosts:  
      hosts:
        devops-vm: # <- Name of server
          ansible_host: 4.223.80.227  #  <- Server IP
          ansible_user: azureuser     # Your SSH username
          ansible_ssh_private_key_file: ~/.ssh/id_boostflow  # Path to SSH key
          server_name: "{{ ansible_host }}"